name: environment_dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cudatoolkit=11.8
  - pytorch-cuda=11.8
  - pytorch>=2.5.1
  - torchvision>=0.20.1
  - numpy<=1.26 
  - torchaudio
  - tqdm
  - plyfile
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python
    - open3d
    - munch
    - trimesh
    - evo
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
