name: MonoGS_Semantic_Dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - tqdm
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
    - -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.1/index.html
    - numpy<2
    - mmengine==0.10.2
    - mmcv==2.1.0
    - mmdet==3.3.0
    - timm
    - regex
    - ftfy
