SEMANTIC_FEATURES_DIM = 64
LSeg_FEATURES_DIM = 512
SAM_FEATURES_DIM = 256
SAM2_FEATURES_DIM = 256
CLIP_FEATURES_DIM = 768

LSeg_IMAGE_SIZE = [360, 480]
CLIP_IMAGE_SIZE = [24, 42]
SAM2_IMAGE_SIZE = [64, 64]

MODE = "CLIP"
Distilled_Feature_DIM = 0
FMAP_SIZE = [680, 1280]
if MODE == "LSeg":
    Distilled_Feature_DIM = LSeg_FEATURES_DIM
    FMAP_SIZE = LSeg_IMAGE_SIZE
elif MODE == "CLIP":
    Distilled_Feature_DIM = CLIP_FEATURES_DIM
    FMAP_SIZE = CLIP_IMAGE_SIZE
elif MODE == "SAM2":
    Distilled_Feature_DIM = SAM2_FEATURES_DIM
    FMAP_SIZE = SAM2_IMAGE_SIZE

MAPPING_START_ITR = 50
MAPPING_ITR = 5